_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 12
                - 45
                - 49
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 12
                - 45
                - 49
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.9
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": darwin-arm64
